# Generated by Django 4.2.4 on 2023-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qrcode', models.ImageField(upload_to='')),
                ('Dateqrcode', models.TextField()),
            ],
        ),
    ]
